# Generated by Django 4.1.5 on 2023-04-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0005_leaves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaves',
            name='leavecount',
        ),
    ]
