# Generated by Django 4.1.5 on 2023-04-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0006_remove_leaves_leavecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='leaves',
            field=models.IntegerField(default=14),
        ),
    ]
