# Generated by Django 4.1.5 on 2023-04-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0007_task_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('TAKEN', 'TAKEN')], default='PENDING', max_length=10),
        ),
    ]
